apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-collector
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-collector
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-collector
    namespace: {{ .Release.Namespace }}
