apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-profiler-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-profiler-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.web }}
          ports:
            - containerPort: 80
          env:
            - name: JAVA_PROFILER_BACKEND_URL
              value: http://{{ .Release.Name }}-backend:{{ .Values.service.port }}
            - name: JAVA_PROFILER_UI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.uiTokenKey }}
