FROM ghcr.io/koolay/library/golang:1.26.0 AS build
WORKDIR /src
COPY go.mod ./
COPY . .
RUN go build -o /out/java-profiler-collector ./cmd/collector

FROM gcr.io/distroless/base-debian12:nonroot
COPY --from=build /out/java-profiler-collector /java-profiler-collector
USER nonroot:nonroot
ENTRYPOINT ["/java-profiler-collector"]
