image:
  collector: ghcr.io/koolay/java-profiler-collector:0.1.0
  backend: ghcr.io/koolay/java-profiler-backend:0.1.0
  web: ghcr.io/koolay/java-profiler-web:0.1.0

clusterName: local

profiling:
  enabledByDefault: false
  startupDelay: 30s
  temporaryMaxDuration: 1h
  snapshotInterval: 5m

clickhouse:
  dsn: tcp://clickhouse:9000/java_profiler

auth:
  existingSecret: java-profiler-auth
  collectorTokenKey: collector-token
  uiTokenKey: ui-token
  tlsSecret: java-profiler-tls

assets:
  asyncProfiler:
    version: "4.2"
    sha256: "4a0097892186730096e7dea6037d9ce706f1e7bb35a7fdbdd951879c42bdfc46"
  threadHelper:
    sha256: "c46abd8e1e151b13e2169b2adef59e8bc84f1357c7a811f454a8172cb2b38481"

service:
  port: 8080

resources:
  collector: {}
  backend: {}
  web: {}
